import { ChurchEvent, Volunteer, Schedule } from '../types';

export const PRODUCTION_ROLES = [
  { id: 'direcao_programa', name: 'Direção de Programa', category: 'Direção' },
  { id: 'backstage', name: 'Backstage', category: 'Palco' },
  { id: 'apoio_preletor', name: 'Apoio ao Preletor', category: 'Palco' },
  { id: 'direcao_imagem', name: 'Direção de Imagem', category: 'Vídeo' },
  { id: 'camera_2', name: 'Câmera 2', category: 'Câmera' },
  { id: 'camera_3', name: 'Câmera 3', category: 'Câmera' },
  { id: 'camera_movel', name: 'Câmera Móvel', category: 'Câmera' },
  { id: 'multimidia_1', name: 'Multimídia 1', category: 'Multimídia' },
  { id: 'multimidia_2', name: 'Multimídia 2 (opcional)', category: 'Multimídia' },
  { id: 'transmissao', name: 'Transmissão', category: 'Streaming' },
  { id: 'instagram', name: 'Instagram', category: 'Redes Sociais' },
  { id: 'mesa_som', name: 'Mesa de Som', category: 'Áudio' },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    name: 'Mateus Albuquerque',
    email: 'mateus.albuquerque@gmail.com',
    phone: '(85) 98721-4411',
    roles: ['Mesa de Som', 'Transmissão'],
    monthlySundayLimit: 2,
    notes: 'Técnico de áudio, opera console digital e FOH.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-2',
    name: 'Larissa Bezerra',
    email: 'larissa.bezerra@gmail.com',
    phone: '(85) 99182-3322',
    roles: ['Direção de Programa', 'Apoio ao Preletor'],
    monthlySundayLimit: 2,
    notes: 'Coordenação geral de culto e alinhamento com pastoral.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-3',
    name: 'Gabriel Holanda',
    email: 'gabriel.holanda@gmail.com',
    phone: '(85) 98845-9988',
    roles: ['Direção de Imagem', 'Transmissão'],
    monthlySundayLimit: 2,
    notes: 'Diretor de TV no switcher e corte de câmeras.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-4',
    name: 'Beatriz Vasconcelos',
    email: 'beatriz.v@gmail.com',
    phone: '(85) 98112-7744',
    roles: ['Multimídia 1', 'Multimídia 2 (opcional)'],
    monthlySundayLimit: 2,
    notes: 'Operadora de projeção de letras e versículos.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-5',
    name: 'Lucas Barreto',
    email: 'lucas.barreto@gmail.com',
    phone: '(85) 99654-1123',
    roles: ['Câmera 2', 'Câmera 3'],
    monthlySundayLimit: 3,
    notes: 'Câmera de pedestal e enquadramento de palco.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-6',
    name: 'Camila Mendes',
    email: 'camila.m@gmail.com',
    phone: '(85) 98789-2231',
    roles: ['Câmera Móvel', 'Instagram'],
    monthlySundayLimit: 2,
    notes: 'Câmera móvel com gimbal e reels de stories ao vivo.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-7',
    name: 'Daniel Farias',
    email: 'daniel.farias@gmail.com',
    phone: '(85) 99234-8855',
    roles: ['Instagram', 'Backstage'],
    monthlySundayLimit: 2,
    notes: 'Mídias sociais e apoio técnico nos bastidores.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'vol-8',
    name: 'Rafael Parente',
    email: 'rafael.parente@gmail.com',
    phone: '(85) 98456-3399',
    roles: ['Backstage', 'Apoio ao Preletor'],
    monthlySundayLimit: 2,
    notes: 'Cuidado com microfones de lapela, água e cronômetro do pastor.',
    createdAt: new Date().toISOString(),
  },
];

// Helper to get formatted dates relative to today
const today = new Date();
const getFutureDate = (daysAhead: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysAhead);
  return d.toISOString().split('T')[0];
};

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: 'event-sun-1',
    title: 'Culto de Celebração (Manhã)',
    type: 'sunday',
    date: getFutureDate(1),
    dates: [getFutureDate(1)],
    time: '10:00',
    location: 'Campus Edson Queiroz - Nave Principal',
    description: 'Culto dominical matutino com transmissão ao vivo completa no YouTube.',
    status: 'scheduled',
    requiredRoles: [
      'Direção de Programa',
      'Mesa de Som',
      'Direção de Imagem',
      'Câmera 2',
      'Câmera 3',
      'Câmera Móvel',
      'Multimídia 1',
      'Transmissão',
      'Instagram',
      'Apoio ao Preletor',
      'Backstage',
    ],
  },
  {
    id: 'event-sun-2',
    title: 'Culto de Celebração (Noite 1)',
    type: 'sunday',
    date: getFutureDate(1),
    dates: [getFutureDate(1)],
    time: '17:00',
    location: 'Campus Edson Queiroz - Nave Principal',
    description: 'Culto dominical de domingo à tarde com louvor congregacional.',
    status: 'scheduled',
    requiredRoles: [
      'Direção de Programa',
      'Mesa de Som',
      'Direção de Imagem',
      'Câmera 2',
      'Câmera 3',
      'Multimídia 1',
      'Transmissão',
      'Apoio ao Preletor',
      'Backstage',
    ],
  },
  {
    id: 'event-sun-3',
    title: 'Culto de Celebração (Noite 2)',
    type: 'sunday',
    date: getFutureDate(1),
    dates: [getFutureDate(1)],
    time: '19:30',
    location: 'Campus Edson Queiroz - Nave Principal',
    description: 'Culto noturno dominical com grande público e transmissão online.',
    status: 'open_for_availability',
    requiredRoles: [
      'Direção de Programa',
      'Mesa de Som',
      'Direção de Imagem',
      'Câmera 2',
      'Câmera 3',
      'Câmera Móvel',
      'Multimídia 1',
      'Multimídia 2 (opcional)',
      'Transmissão',
      'Instagram',
      'Apoio ao Preletor',
      'Backstage',
    ],
  },
  {
    id: 'event-conf-1',
    title: 'Conferência de Avivamento IBC (2 Dias)',
    type: 'weekday',
    date: getFutureDate(4),
    dates: [getFutureDate(4), getFutureDate(5)],
    time: '19:30',
    location: 'Campus Edson Queiroz - Nave Principal',
    description: 'Evento especial de mais de um dia. Os servos podem escolher em quais dias estão disponíveis!',
    status: 'open_for_availability',
    requiredRoles: [
      'Direção de Programa',
      'Mesa de Som',
      'Direção de Imagem',
      'Câmera 2',
      'Câmera Móvel',
      'Multimídia 1',
      'Transmissão',
      'Instagram',
    ],
  },
  {
    id: 'event-wed-1',
    title: 'Quarta Profética & Oração',
    type: 'weekday',
    date: getFutureDate(4),
    dates: [getFutureDate(4)],
    time: '19:30',
    location: 'Campus Edson Queiroz - Auditório 1',
    description: 'Culto de oração na quarta-feira. Não desconta do limite mensal de domingos!',
    status: 'open_for_availability',
    requiredRoles: [
      'Mesa de Som',
      'Multimídia 1',
      'Apoio ao Preletor',
      'Direção de Programa',
    ],
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sched-1',
    eventId: 'event-sun-1',
    eventTitle: 'Culto de Celebração (Manhã)',
    eventDate: getFutureDate(1),
    eventTime: '10:00',
    eventType: 'sunday',
    leaderName: 'Liderança de Produção IBC',
    leaderId: 'leader-1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: 'Chegada pontual às 08h45 para oração e passagem de som.',
    assignments: [
      {
        roleId: 'direcao_programa',
        roleName: 'Direção de Programa',
        volunteerId: 'vol-2',
        volunteerName: 'Larissa Bezerra',
        volunteerPhone: '(85) 99182-3322',
        attendanceStatus: 'confirmed',
      },
      {
        roleId: 'mesa_som',
        roleName: 'Mesa de Som',
        volunteerId: 'vol-1',
        volunteerName: 'Mateus Albuquerque',
        volunteerPhone: '(85) 98721-4411',
        attendanceStatus: 'confirmed',
      },
      {
        roleId: 'direcao_imagem',
        roleName: 'Direção de Imagem',
        volunteerId: 'vol-3',
        volunteerName: 'Gabriel Holanda',
        volunteerPhone: '(85) 98845-9988',
        attendanceStatus: 'confirmed',
      },
      {
        roleId: 'camera_2',
        roleName: 'Câmera 2',
        volunteerId: 'vol-5',
        volunteerName: 'Lucas Barreto',
        volunteerPhone: '(85) 99654-1123',
        attendanceStatus: 'scheduled',
      },
      {
        roleId: 'multimidia_1',
        roleName: 'Multimídia 1',
        volunteerId: 'vol-4',
        volunteerName: 'Beatriz Vasconcelos',
        volunteerPhone: '(85) 98112-7744',
        attendanceStatus: 'confirmed',
      },
      {
        roleId: 'apoio_preletor',
        roleName: 'Apoio ao Preletor',
        volunteerId: 'vol-8',
        volunteerName: 'Rafael Parente',
        volunteerPhone: '(85) 98456-3399',
        attendanceStatus: 'scheduled',
      },
    ],
  },
];
